version: '3.8'

services:
  worker-node:
    image: ghcr.io/energywebfoundation/ewx-worker-node-server/ewx-worker-node-server:latest
    ports:
      - '3002:3002'
    environment:
      - PALLET_RPC_URL=${PALLET_RPC_URL}
      - VOTING_RPC_URL=${VOTING_RPC_URL}
      - VOTING_WORKER_SEED=${VOTING_WORKER_SEED}
      - IPFS_API_KEY=${IPFS_API_KEY}
      - IPFS_SECRET_KEY=${IPFS_SECRET_KEY}
      - IPFS_URL=${IPFS_URL}
      - IPFS_CONTEXT_PATH=${IPFS_CONTEXT_PATH}
