version: '3.8'

services:
  worker-node:
    image: ghcr.io/energywebfoundation/ewx-worker-node-server/ewx-worker-node-server:latest
    ports:
      - '3002:3002'
    environment:
      - PALLET_RPC_URL=${PALLET_RPC_URL}
      - VOTING_RPC_URL=${VOTING_RPC_URL}
      - VOTING_WORKER_SEED=${VOTING_WORKER_SEED}
