name: Release EWX Worker Node (Test)

on:
  push:

env:
  IMAGE_NAME: ${{ secrets.EWX_WORKER_NODE_SERVER }}
  AWS_REGION: us-east-1

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  docker-build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [cancel-previous]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          # Extract branch name from GITHUB_REF
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # For tags
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            # For branches
            echo "VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          else
            # For pull requests and others
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi
          echo "Branch/tag: ${{ steps.extract_branch.outputs.VERSION }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          mask-aws-account-id: true

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.VERSION }}
